// typedef char[32] plugin_event_t;

enum PluginEvents
{
	// plugin handling events

	// PLUGINS_ONINIT,
	PLUGINS_ONINFOREQUEST,

	// runtime events:

	PLUGINS_ONPLAYERDC,
	PLUGINS_ONPLAYERCONNECT,
	PLUGINS_ONEXITLEVEL,
	PLUGINS_ONMESSAGESENT,
	PLUGINS_ONFRAME,	 // new
	PLUGINS_ONONESECOND, // new
	PLUGINS_ONTENSECONDS,
	PLUGINS_ONCLIENTAUTHORIZED, // new
	PLUGINS_ONCLIENTSPAWN,
	PLUGINS_ONCLIENTENTERWORLD,
	PLUGINS_ONTCPSERVERPACKET, // new
	PLUGINS_ONUDPNETEVENT,
	PLUGINS_ONUDPNETSEND,
	PLUGINS_ONSPAWNSERVER,
	PLUGINS_ONPREFASTRESTART,
	PLUGINS_ONPOSTFASTRESTART,
	PLUGINS_ONPREGAMERESTART,
	PLUGINS_ONPOSTGAMERESTART,
	PLUGINS_ONCLIENTUSERINFOCHANGED,
	PLUGINS_ONCLIENTCOMMAND,
	PLUGINS_ONCLIENTMOVECOMMAND,
	PLUGINS_ONPLAYERKILLED,
	PLUGINS_ONPLAYERWANTRESERVEDSLOT,
	PLUGINS_ONFSSTARTED,
	PLUGINS_ONPLAYERGOTAUTHINFO,
	PLUGINS_ONPLAYERADDBAN,
	PLUGINS_ONPLAYERGETBANSTATUS,
	PLUGINS_ONPLAYERREMOVEBAN,
	PLUGINS_ONMODULELOADED,
	PLUGINS_ONSCREENSHOTARRIVED,
	PLUGINS_ONTERMINATE,
	PLUGINS_ITEMCOUNT

};

extern char PHandler_Events[PLUGINS_ITEMCOUNT][32]; // defined in plugin_handler.c
